### ISSUE TITLE
freemoji broken atm

### ISSUE THREAD

**Issue by ogmicco** [yellowsink/shelter-plugins#1]
freemoji doesn't work, I can send any emoji I want but it displays it like this:
![image](https://user-images.githubusercontent.com/107354268/207589684-eafd970c-5421-4386-8f56-09d684261f75.png)

**Comment by yellowsink** [comment]
Yeah, freemoji is a bit temperamental, I've been meaning to look more into it but have been doing other things

**Comment by ogmicco** [comment]
hope u can look into it soon. Amazing plugin :)

**Comment by aaronliu0130** [comment]
i can also confirm
