### ISSUE TITLE
Freemoji Reloaded plugins sticker is not working properly

### ISSUE THREAD

**Issue by BaranKral** [yellowsink/shelter-plugins#11]
The sticker part of the freemoji plugin is not working, it sends but does not go to the other side

**Comment by DeadLyBro** [comment]
Same. I got;
`error` : `403 Forbidden`
`code` : `50081`
`message` : `Cannot use this sticker`

Note: I'm sure I have send link permission.

**Comment by yellowsink** [comment]
freemoji does not handle stickers at all.
freemoji COULD do with a rewrite in all honesty but yeah not atm

the cumcord one used to but it was [very in depth](https://github.com/sink-cord-archive/cc-plugins/blob/master/plugins/emoji-free/patches/stickers.js) and replicating it in shelter is kind of impractical sadly, especially animated ones which never worked on cc either.

I don't plan to add sticker support as is, if anyone wants to feel free to PR, if i rewrite it to take advantage of http interception maybe ill consider it but for now, wontfix
