### ISSUE TITLE
[Freemoji] <Enhancement> No size tag

### ISSUE THREAD

**Issue by aaronliu0130** [yellowsink/shelter-plugins#12]
Could an option to not specify any size at all, e.g. https://cdn.discordapp.com/emojis/1145141919800400418.webp instead of https://cdn.discordapp.com/emojis/1145141919800400418.webp?size=[size], be added?

**Comment by DeadLyBro** [comment]
If there is no size tag, some emojis may look too big, so I think it is necessary.

**Comment by aaronliu0130** [comment]
Freemojis work best when on their own, like a gif. When you send a gif, you want it to be the max size possible, which is capped by Discord anyways.

**Comment by DeadLyBro** [comment]
Yeah, you're right. I don't think Gifs. My silly head :D

**Comment by DeadLyBro** [comment]
Actually there is a settings button, so If you want just increase the size? 
![image](https://github.com/yellowsink/shelter-plugins/assets/31214077/c66d7925-a4f4-4165-921d-d3f9d991f38d)

Wait, I tried now, and it send gifs with their own Width and Height? So you actually doesn't need for that?

**Comment by aaronliu0130** [comment]
The settings sets the size to [size], like the second link I sent above. I want to be able to send them in their native resolution.

**Comment by DeadLyBro** [comment]
And I said it's not necessary because Gifs are sending their own width and height. ( I tried. )

**Comment by DeadLyBro** [comment]
If you're talking about emoji's, you don't need for change size.

**Comment by yellowsink** [comment]
Just set it to something like 4096
discord wont upscale images, only downscale them.
setting the size to 9999999 will cause them to send in their native resolution

**Comment by aaronliu0130** [comment]
4096 is a good idea! Anything bigger (including 8192 and 9999999) causes the link to give an error and not load though.
