### ISSUE TITLE
[invidivizer] instance shutting down

### ISSUE THREAD

**Issue by Puyodead1** [yellowsink/shelter-plugins#24]
the current invidious instance being used is apparently being shut down (inv.n8pjl.ca), and embeds no longer work. I know you can change it in the config, but I wanted to give you a heads up about changing the default.

https://github.com/iv-org/documentation/issues/560#issuecomment-2287199044

![image](https://github.com/user-attachments/assets/f2f7c3bf-1843-42c1-8765-ecc9e9949a77)

**Comment by NekoAlosama** [comment]
@yellowsink
