### ISSUE TITLE
Timestamp tweaks doesn't accept older user IDs/snowflakes

### ISSUE THREAD

**Issue by Razzaline** [yellowsink/shelter-plugins#3]
I tried adding a user ID with 17 digits, but it wouldn't accept it. It turns out old Discord accounts (like my original one) have 17 digits, then they added one more, and just 8 months ago they added another, making it 19.

https://www.reddit.com/r/discordapp/comments/w47zyx/fun_fact_discord_is_about_to_add_another_digit_to/

Edit: 19 digit IDs don't work either.

**Comment by yellowsink** [comment]
Oh I see, I was unaware of this, thanks for the heads up, I'll get that fixed!
