### ISSUE TITLE
[Antitrack] Needs a better description.

### ISSUE THREAD

**Issue by NekoAlosama** [yellowsink/shelter-plugins#32]
![image](https://github.com/user-attachments/assets/54926563-ae50-4e82-b8d0-93b481bcb7c7)
Honestly, with how broken some of these plugins are, I thought that this was actually a dependency.

**Comment by yellowsink** [comment]
if you to report an issue to me maybe don't be such an ass with your wording
i'm not dealing with this shit after youve bumped like 4 of my issues fuck the hell off
