### ISSUE TITLE
[Pronoundb] Compact formatting is wack

### ISSUE THREAD

**Issue by skifli** [yellowsink/shelter-plugins#33]
The pronoundb plugin when enabled with compact mode is not formatted correctly - the pronoun(s) and time span multiple lines:

![image](https://github.com/user-attachments/assets/714ab4d5-f97f-40e0-8fab-74cd0472a0ef)

**Comment by yellowsink** [comment]
thanks for the report!

**Comment by skifli** [comment]
Nw.
