### ISSUE TITLE
[Enhancement] Timestamp tweaks: Allow editing of manual user time zone entries

### ISSUE THREAD

**Issue by Razzaline** [yellowsink/shelter-plugins#4]
At the moment, I have to delete and re-add entries if I want to change them. I think it would be helpful to be able to edit them. Thanks!

**Comment by yellowsink** [comment]
I would like to get this added, I just need to figure out how the UI will work as I still want to handle validation properly

Maybe a proper timezone picker with a world map or something might be better, since its kind of hard to know what regions are what anyway (since using things like America/New_York will give you daylight savings as opposed to EST)

**Comment by Razzaline** [comment]
Oh, speaking of validation, having a message dialog come up saying the ID or time zone failed verification would be helpful too. There's no indicator at the moment so you kind of have to guess what's off.

I think that could work! That's how I remember the Cinnamon DE doing it when I was on Linux Mint (sadly KDE doesn't seem to do that). That did make it more intuitive. At first I didn't realise I was supposed to type the time zones in that format, so I was trying stuff like EST or NZT and wondering why it didn't work.

Also, it's not really necessary, but I'm wondering if the entries could be sorted (either manually or alphabetically or something like that).

**Comment by yellowsink** [comment]
I was thinking of this sort of deal!
![78A0E7CC-F786-4199-99BD-D8ABA74E5AD1](https://user-images.githubusercontent.com/19270622/230039985-d7f31529-4ec2-4459-be69-4bdc85c9c1f8.jpeg)

**Comment by yellowsink** [comment]
But yeah sounds good

**Comment by yellowsink** [comment]
Fixed in 3a62d15

**Comment by Razzaline** [comment]
Looking forward to using it! Thank you for such a quick response. c:

**Comment by yellowsink** [comment]
no problem :)
