### ISSUE TITLE
[Enhancement] Timezone tweaks: custom time format for other users' relative time

### ISSUE THREAD

**Issue by Razzaline** [yellowsink/shelter-plugins#5]
Sorry to open another one, but I was thinking it'd be useful to be able to set the time format for the relative time for other users. I was thinking some time zones will be on a different day and it might help to know what their date is relative to yours.

**Comment by RoseIlanga** [comment]
Oh, as in show the whole date if you want for a given user (e.g. 2023/11/10 19:38)? That could be useful, yeah. No idea how easy it would be to implement, though.

**Comment by NekoAlosama** [comment]
@yellowsink

**Comment by yellowsink** [comment]
I have a busy life, please do not ping me under multiple issues

**Comment by yellowsink** [comment]
im sorry that this took literally a year and a half to get around to, it's done :)

**Comment by RoseIlanga** [comment]
No problem. I know how that can be. I'm glad you were able to get it done, though. c:
