### ISSUE TITLE
Timestamp tweaks crashes

### ISSUE THREAD

**Issue by samjaninf** [yellowsink/shelter-plugins#6]
Something about timestamp tweaks causes my discord to break and freeze and be unusable. I don't quite know how to debug it.

**Comment by yellowsink** [comment]
Hmm, interesting. any console logs or no?

I'll take a look at possible causes of infinite loops and the like - I can probably calm down some particularly noisy Flux listeners...

**Comment by Bulldog3321** [comment]
happens to me too, seems to happen more often on channels with lots of long messages. cant open the console to check errors while its frozen

**Comment by yellowsink** [comment]
Fixed in https://github.com/uwu/shelter/commit/93499fe03cc93f7e7b4b4e4b551973aa895413fe
