### ISSUE TITLE
QuickReply Reloaded functionalty

### ISSUE THREAD

**Issue by samjaninf** [yellowsink/shelter-plugins#8]
I guess this is a feature request? I don't know if you take requests (I haven't had the time to try and write plugin so I don't know how to)

But the functionality where it disables the auto ping back for messages:
![image](https://user-images.githubusercontent.com/6589200/235417848-ef237b04-f651-4f3b-a19c-8fc943ca53fb.png)

I was wondering if it were possible to extend that to the normal action when you click reply.

**Comment by yellowsink** [comment]
Should be relatively doable - I'll look into it I guess :)

**Comment by yellowsink** [comment]
https://github.com/SpikeHD/shelter-plugins#no-reply-mention
